site_name: "DePSI: Delft PS-InSAR processing package"
repo_url: https://github.com/TUDelftGeodesy/DePSI
repo_name: DePSI

nav:
  - Getting started: 
    - About DePSI: index.md
  - Usage:
    - Load data: usages/io.md
    - Select PS and DS: usages/classification.md
    - Quality improvement: usages/quality.md
    - Network unwrapping: usages/network.md
  - Contributing: 
    - Contributing guide: CONTRIBUTING.md
    - Practical info for developers: dev_guide.md
    - Code of conduct: CODE_OF_CONDUCT.md
  - Example Notebooks:
    - SARXarray and STMTools Dependencies of DePSI: notebooks/demo_sarxarray_and_stmtools.ipynb
    - DePSI example workflow: notebooks/demo_depsi.ipynb


theme:
  name: material
  custom_dir: docs/notebooks/download_button
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue
      accent: white

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: pink
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  
plugins:
- mkdocs-jupyter:
      include_source: True
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          docstring_options:
            ignore_init_summary: no
          merge_init_into_class: yes
          show_submodules: no

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra:
  generator: false
  version:
    provider: mike